# .streamlit/config.toml

[theme]
# The primary accent color for interactive elements.
primaryColor="#7A4DFF"

# Background color for the main content area.
backgroundColor="#0E1117"

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor="#262730"

# Color for most text.
textColor="#FAFAFA"

# Font family for all text in the app.
font="sans serif"